name = "vcpu-stress-test"
main = "dist/worker.js"
compatibility_date = "2024-09-17"

[build]
command = "npm run build"
watch_dir = "src"

[vars]
VCPU_TEST = "auto-configured"
PLAN_TYPE = "auto-detected"

[env.development]
name = "vcpu-stress-test-dev"

[env.production] 
name = "vcpu-stress-test-prod"
